version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}
  django_staticfiles: {}

services:
  nginx:
    image: nginx:1.27
    restart: unless-stopped
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/docker/ssl:/etc/ssl
      - ./compose/production/nginx/djangocms.conf:/etc/nginx/conf.d/djangocms.conf
      - django_staticfiles:/var/staticfiles
      - production_django_media:/var/media
    env_file:
      - ./.envs/.production/.nginx

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: djangocms_ndthemev4_production_django
    volumes:
      - production_django_media:/app/samplecms/media
      - django_staticfiles:/var/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: djangocms_ndthemev4_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:alpine

  celeryworker:
    <<: *django
    image: djangocms_ndthemev4_production_celeryworker
    container_name: djangocms_ndthemev4_production_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: celery -A config.celery_app worker -l info -Q celery

  celerybeat:
    <<: *django
    image: djangocms_ndthemev4_production_celerybeat
    container_name: djangocms_ndthemev4_production_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat
