# Generated by Django 6.1 on 2026-08-07 14:17

import cms.models.fields
import django.db.models.deletion
import djangocms_text.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='EmailLink',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=4096)),
                ('link', models.CharField(max_length=4096)),
                ('description', djangocms_text.fields.HTMLField(blank=True, null=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FullWidthImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=4096, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('google_maps_link', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('search_category', models.BooleanField(default=False)),
                ('archive_category', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageTagPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PersonListItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('phone_number', models.CharField(max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SideNavigationDynamicFilter',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SimpleText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(max_length=2048)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ArchivePageExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_now', models.BooleanField(default=False)),
                ('schedule_archive', models.DateTimeField(blank=True, null=True)),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ButtonLink',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(max_length=255)),
                ('external_link', models.CharField(blank=True, max_length=4096, null=True)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_series_record', to='cms.page')),
            ],
            options={
                'verbose_name_plural': 'Event Series',
            },
        ),
        migrations.CreateModel(
            name='PageContentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='PagePreviewExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('image_caption', models.CharField(blank=True, max_length=255, null=True)),
                ('summary_caption', models.CharField(blank=True, help_text='Shown as summaries in lists and cards linking to this page.', max_length=2048, null=True)),
                ('publish_date', models.DateField(blank=True, help_text="Overrides the page's creation date when sorting News/People listings and archives. django CMS 5 no longer tracks a separate page publication date.", null=True)),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('tags', models.ManyToManyField(blank=True, related_name='pages', to='ndthemes.pagetag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventsInsert',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('further_reading_link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('events_after_date', models.DateField(blank=True, null=True)),
                ('events_before_date', models.DateField(blank=True, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('further_reading_link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('tags', models.ManyToManyField(blank=True, related_name='event_filters', to='ndthemes.pagetag')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('events_after_date', models.DateField(blank=True, null=True)),
                ('events_before_date', models.DateField(blank=True, null=True)),
                ('child_events_only', models.BooleanField(default=False)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('view_more_link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('view_more_link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_list_view_more_link', to='cms.page')),
                ('tags', models.ManyToManyField(blank=True, related_name='event_list_filters', to='ndthemes.pagetag')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ChildPageList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('order', models.CharField(blank=True, choices=[('name-asc', 'Title (A → Z)'), ('name-desc', 'Title (Z → A)'), ('date-asc', 'Publication Date (Newest → Oldest)'), ('date-desc', 'Publication Date (Oldest → Newest)')], max_length=255, null=True)),
                ('show_publication_date', models.BooleanField(default=False)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('view_more_link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_page', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_page_list_parent_page', to='cms.page')),
                ('view_more_link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_page_list_view_more_link', to='cms.page')),
                ('tags', models.ManyToManyField(blank=True, related_name='child_page_list_filters', to='ndthemes.pagetag')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ArchiveLink',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(max_length=255)),
                ('optional_tags', models.ManyToManyField(blank=True, related_name='archive_link_filters', to='ndthemes.pagetag')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PersonListGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('order', models.CharField(choices=[('name-asc', 'Name (A → Z)'), ('name-desc', 'Name (Z → A)'), ('position-asc', 'Position (A → Z)'), ('position-desc', 'Position (Z → A)')], default='name-asc', max_length=255)),
                ('tags', models.ManyToManyField(blank=True, related_name='person_grid_list_filters', to='ndthemes.pagetag')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PersonListStacked',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('order', models.CharField(choices=[('name-asc', 'Name (A → Z)'), ('name-desc', 'Name (Z → A)'), ('position-asc', 'Position (A → Z)'), ('position-desc', 'Position (Z → A)')], default='name-asc', max_length=255)),
                ('tags', models.ManyToManyField(blank=True, related_name='person_list_stacked_filters', to='ndthemes.pagetag')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('map_link', models.CharField(blank=True, max_length=4096, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_record', to='cms.page')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ndthemes.eventseries')),
                ('recurring_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ndthemes.recurringevent')),
            ],
        ),
        migrations.CreateModel(
            name='Ribbon',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, max_length=4096, null=True)),
                ('link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=4096, null=True)),
                ('internal_link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RibbonImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('external_link', models.CharField(blank=True, max_length=4096, null=True)),
                ('link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=4096, null=True)),
                ('internal_link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RibbonImageAlt',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('external_link', models.CharField(blank=True, max_length=4096, null=True)),
                ('link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=4096, null=True)),
                ('internal_link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('setting_type', models.CharField(choices=[('text', 'Text'), ('boolean', 'True/False'), ('page', 'Page')], default='text', max_length=255)),
                ('page', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='SideNavigationChildList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('link_order', models.CharField(blank=True, choices=[('page-tree', 'Page Order'), ('name-asc', 'Title (A → Z)'), ('name-desc', 'Title (Z → A)'), ('date-asc', 'Publication Date (Newest → Oldest)'), ('date-desc', 'Publication Date (Oldest → Newest)')], default='page-tree', max_length=255, null=True)),
                ('show_second_level_children', models.BooleanField(default=False)),
                ('child_link_order', models.CharField(blank=True, choices=[('page-tree', 'Page Order'), ('name-asc', 'Title (A → Z)'), ('name-desc', 'Title (Z → A)'), ('date-asc', 'Publication Date (Newest → Oldest)'), ('date-desc', 'Publication Date (Oldest → Newest)')], default='page-tree', max_length=255, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='side_navigation_child_list_filters', to='ndthemes.pagetag')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SideNavigationPageLink',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('page', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_navigation_page_link', to='cms.page')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Triptych',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('further_reading_link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('center_card', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_card', to='cms.page')),
                ('further_reading_link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('left_card', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_card', to='cms.page')),
                ('right_card', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_card', to='cms.page')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
