# Generated by Django 6.1 on 2026-08-07 16:16

import django.db.models.deletion
import djangocms_text.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
        ('ndthemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('size', models.CharField(blank=True, choices=[('', 'Default'), ('sm', 'Small'), ('lg', 'Large')], default='', max_length=16)),
                ('style', models.CharField(blank=True, choices=[('', 'Default'), ('highlight', 'Highlighted'), ('bg', 'With background')], default='', max_length=16)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255)),
                ('open_by_default', models.BooleanField(default=False)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('level', models.CharField(choices=[('1', 'Heading 1'), ('2', 'Heading 2'), ('3', 'Heading 3'), ('4', 'Heading 4'), ('5', 'Heading 5'), ('6', 'Heading 6')], default='2', max_length=1)),
                ('text', models.CharField(max_length=512)),
                ('css_class', models.CharField(blank=True, default='', help_text='Optional extra classes (e.g. section-title).', max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('variant', models.CharField(blank=True, choices=[('', 'Default'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='', max_length=16)),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('body', djangocms_text.fields.HTMLField(blank=True, default='')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('quote', djangocms_text.fields.HTMLField()),
                ('citation', models.CharField(blank=True, default='', max_length=512)),
                ('size', models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra large')], default='md', max_length=8)),
                ('alignment', models.CharField(blank=True, choices=[('', 'Default'), ('centered', 'Centered'), ('right', 'Right'), ('reversed', 'Reversed')], default='', max_length=16)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('xs', 'Extra small'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', max_length=8)),
                ('centered', models.BooleanField(default=False)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
