# Generated by Django 6.1 on 2026-08-07 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
        ('ndthemes', '0002_m5_component_plugins'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('columns', models.CharField(choices=[('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns')], default='3', max_length=1)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
