# Generated by Django 6.1 on 2026-08-07 16:25

import django.db.models.deletion
import djangocms_text.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
        ('ndthemes', '0003_m5_stat_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('list_type', models.CharField(choices=[('unordered', 'Unordered'), ('ordered', 'Ordered'), ('unstyled', 'Unstyled'), ('inline', 'Inline'), ('stepped', 'Stepped'), ('spaced', 'Spaced')], default='unordered', max_length=16)),
                ('label', models.CharField(blank=True, default='', help_text='Optional label shown above the list.', max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', djangocms_text.fields.HTMLField(blank=True, default='')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('style', models.CharField(blank=True, choices=[('', 'Default'), ('minimal', 'Minimal')], default='', max_length=16)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('body', djangocms_text.fields.HTMLField(help_text='Table markup without the outer <table> tag (use thead/tbody rows).')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TabPanel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255)),
                ('active_by_default', models.BooleanField(default=False)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('size', models.CharField(blank=True, choices=[('', 'Default'), ('lg', 'Large')], default='', max_length=8)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('alignment', models.CharField(blank=True, choices=[('', 'Default'), ('right', 'Right'), ('center', 'Center')], default='', max_length=16)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, default='', max_length=128)),
                ('body', djangocms_text.fields.HTMLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ndthemes/timeline/')),
                ('image_alt', models.CharField(blank=True, default='', max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
