# Generated by Django 6.1 on 2026-08-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
        ('ndthemes', '0004_m5_tabs_list_table_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='ndthemes/avatars/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.CharField(choices=[('xs', 'Extra small'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra large')], default='md', max_length=8)),
                ('style', models.CharField(blank=True, choices=[('', 'Default'), ('quote', 'Quote')], default='', max_length=16)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('style', models.CharField(blank=True, choices=[('', 'Default grid'), ('tiled', 'Tiled'), ('tiled-alt', 'Tiled (alternate)'), ('slider', 'Slider')], default='', max_length=16)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='ndthemes/gallery/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', help_text='Lightbox title.', max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ImageMultiple',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('layout', models.CharField(choices=[('tiled', 'Tiled'), ('mosaic', 'Mosaic'), ('mosaic-reversed', 'Mosaic (reversed)')], default='tiled', max_length=16)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ImageMultipleItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='ndthemes/images/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ImageSingle',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='ndthemes/images/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=4096)),
                ('layout', models.CharField(blank=True, choices=[('', 'Default'), ('full-width', 'Full width'), ('left', 'Float left'), ('right', 'Float right'), ('circle', 'Circle')], default='', max_length=16)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('display_type', models.CharField(choices=[('embed', 'Embedded player'), ('placeholder', 'Placeholder with play button')], default='embed', max_length=16)),
                ('video_url', models.URLField(help_text='YouTube or Vimeo URL.')),
                ('label', models.CharField(blank=True, default='', help_text='Label for placeholder style.', max_length=255)),
                ('style', models.CharField(choices=[('default', 'Default'), ('minimal', 'Minimal'), ('outline', 'Outline'), ('ornamental', 'Ornamental')], default='default', max_length=16)),
                ('alignment', models.CharField(blank=True, choices=[('', 'Default'), ('left', 'Float left'), ('right', 'Float right')], default='', max_length=16)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
