# Generated by Django 6.1 on 2026-08-07 16:32

import cms.models.fields
import django.db.models.deletion
import djangocms_text.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
        ('ndthemes', '0005_m5_media_plugins'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonGroup',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('style', models.CharField(blank=True, choices=[('', 'Default'), ('border', 'With dividers')], default='', max_length=16)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ButtonList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('size', models.CharField(blank=True, choices=[('', 'Default'), ('sm', 'Small'), ('lg', 'Large')], default='', max_length=8)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FootnoteItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('body', djangocms_text.fields.HTMLField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FootnoteList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavAnchor',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, default='Anchor', max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Pagination',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ButtonItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('text', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='IconButton',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('text', models.CharField(max_length=255)),
                ('icon', models.CharField(choices=[('arrow-right', 'Arrow right'), ('external-link', 'External link'), ('download', 'Download'), ('envelope', 'Envelope')], default='arrow-right', max_length=32)),
                ('alignment', models.CharField(blank=True, choices=[('', 'Left'), ('right', 'Right')], default='', max_length=16)),
                ('reveal_on_hover', models.BooleanField(default=True)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='LedeButton',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('text', models.CharField(max_length=512)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='NavAnchorItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('text', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='PaginationItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('label', models.CharField(max_length=32)),
                ('item_type', models.CharField(choices=[('page', 'Page'), ('current', 'Current page'), ('disabled', 'Disabled'), ('previous', 'Previous'), ('next', 'Next')], default='page', max_length=16)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
