# Generated by Django 6.1 on 2026-08-07 16:39

import cms.models.fields
import django.db.models.deletion
import djangocms_text.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
        ('ndthemes', '0006_m5_buttons_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('trigger_text', models.CharField(default='Open dialog', max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('body', djangocms_text.fields.HTMLField()),
                ('footer', models.TextField(blank=True, default='')),
                ('style', models.CharField(blank=True, choices=[('', 'Default'), ('narrow', 'Narrow'), ('alert', 'Alert'), ('notification', 'Notification'), ('person', 'With person'), ('video', 'With video')], default='', max_length=16)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('show_anchors', models.BooleanField(default=True)),
                ('anchors_id', models.CharField(default='faq-list', help_text='ID for the anchor navigation list.', max_length=64)),
                ('show_back_to_top', models.BooleanField(default=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('question', models.CharField(max_length=512)),
                ('item_id', models.CharField(help_text='Anchor ID for this item (e.g. faq_001).', max_length=64)),
                ('answer', djangocms_text.fields.HTMLField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PageHeader',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=512)),
                ('lede', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ndthemes/page-headers/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('title_size', models.CharField(blank=True, choices=[('', 'Default'), ('sm', 'Small'), ('lg', 'Large'), ('xl', 'Extra large')], default='', max_length=8)),
                ('variant', models.CharField(blank=True, choices=[('', 'Default'), ('inset', 'Inset'), ('container', 'Container'), ('screen', 'Screen'), ('fade', 'Fade'), ('mosaic', 'Mosaic'), ('tiled', 'Tiled')], default='', max_length=16)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('layout', models.CharField(choices=[('stacked', 'Stacked'), ('default', 'Default (side by side)'), ('full', 'Full width')], default='stacked', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('caption', djangocms_text.fields.HTMLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ndthemes/banners/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('link_text', models.CharField(blank=True, default='Learn more', max_length=255)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
