# Generated by Django 6.1 on 2026-08-07 18:41

import cms.models.fields
import django.db.models.deletion
import djangocms_text.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
        ('ndthemes', '0007_m5_dialog_faq_banner_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CardBylineItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', help_text='Role or affiliation', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ndthemes/cards/')),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='CardDefault',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('style', models.CharField(blank=True, choices=[('', 'Default'), ('horizontal', 'Horizontal'), ('compact', 'Compact'), ('border', 'Border'), ('image-sm', 'Small image'), ('stacked', 'Stacked'), ('image-right', 'Image right')], default='', max_length=16)),
                ('title', models.CharField(max_length=512)),
                ('summary', djangocms_text.fields.HTMLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ndthemes/cards/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=512)),
                ('recurring', models.BooleanField(default=False)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='CardFeatured',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ndthemes/cards/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='CardMediaMention',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('publication_name', models.CharField(max_length=255)),
                ('publication_slug', models.CharField(blank=True, default='', help_text='Optional CSS class for publication styling (e.g. npr, nyt).', max_length=64)),
                ('publication_logo', models.ImageField(blank=True, null=True, upload_to='ndthemes/publications/')),
                ('title', models.CharField(max_length=512)),
                ('summary', djangocms_text.fields.HTMLField(blank=True, default='')),
                ('mention_date', models.CharField(blank=True, default='', max_length=64)),
                ('meta_heading', models.CharField(blank=True, default='Mentions', max_length=64)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='CardMediaMentionQuoted',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('publication_name', models.CharField(max_length=255)),
                ('publication_slug', models.CharField(blank=True, default='', max_length=64)),
                ('publication_logo', models.ImageField(blank=True, null=True, upload_to='ndthemes/publications/')),
                ('quote', djangocms_text.fields.HTMLField()),
                ('link_text', models.CharField(default='Read article', max_length=64)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='CardNews',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('style', models.CharField(blank=True, choices=[('', 'Default'), ('horizontal', 'Horizontal'), ('compact', 'Compact'), ('border', 'Border'), ('image-sm', 'Small image'), ('stacked', 'Stacked'), ('image-right', 'Image right')], default='', max_length=16)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('summary', djangocms_text.fields.HTMLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ndthemes/cards/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='CardPerson',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('style', models.CharField(blank=True, choices=[('', 'Default'), ('horizontal', 'Horizontal'), ('compact', 'Compact'), ('border', 'Border'), ('image-sm', 'Small image'), ('stacked', 'Stacked'), ('image-right', 'Image right')], default='', max_length=16)),
                ('title', models.CharField(help_text='Person name', max_length=512)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', djangocms_text.fields.HTMLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ndthemes/cards/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
