# Generated by Django 6.1 on 2026-08-07 19:13

import cms.models.fields
import django.db.models.deletion
import djangocms_text.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
        ('ndthemes', '0008_m5_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAccordionItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255)),
                ('body', djangocms_text.fields.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ndthemes/banners/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('open_by_default', models.BooleanField(default=False)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BannerImageItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='ndthemes/banners/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('submit_label', models.CharField(default='Submit', max_length=64)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('password', 'Password'), ('number', 'Number'), ('date', 'Date'), ('search', 'Search'), ('textarea', 'Textarea'), ('select', 'Select'), ('checkbox_list', 'Checkbox list'), ('radio_list', 'Radio list'), ('switch', 'Switch')], default='text', max_length=16)),
                ('field_id', models.SlugField(help_text='Unique field id for labels/inputs.', max_length=64)),
                ('input_placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('options', models.TextField(blank=True, default='', help_text='One option per line (for select, checkbox, radio).')),
                ('required', models.BooleanField(default=False)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('icon', models.CharField(choices=[('search', 'Search'), ('arrow-right', 'Arrow right'), ('external-link', 'External link'), ('download', 'Download'), ('envelope', 'Envelope'), ('clock', 'Clock'), ('map-pin', 'Map pin'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter-x', 'X/Twitter'), ('box-arrow-up', 'Share')], default='arrow-right', max_length=32)),
                ('size', models.CharField(blank=True, choices=[('', 'Default'), ('sm', 'Small'), ('lg', 'Large'), ('xl', 'Extra large')], default='', max_length=8)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SearchForm',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(default='Search', help_text='Accessible label for the search field.', max_length=255)),
                ('input_placeholder', models.CharField(blank=True, default='Search…', max_length=255)),
                ('action', models.CharField(blank=True, default='/search/', max_length=512)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SocialShare',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('sticker', models.CharField(choices=[('backpack', 'Backpack'), ('chalk-board', 'Chalk board'), ('dna', 'DNA'), ('football', 'Football'), ('globe', 'Globe'), ('grad-cap', 'Grad cap'), ('library', 'Library'), ('microscope', 'Microscope')], default='backpack', max_length=32)),
                ('size', models.CharField(blank=True, choices=[('', 'Default'), ('sm', 'Small'), ('lg', 'Large'), ('xl', 'Extra large')], default='', max_length=8)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='banner',
            name='intro_alignment',
            field=models.CharField(blank=True, default='', help_text='Optional intro alignment class (e.g. "text-center").', max_length=16),
        ),
        migrations.AddField(
            model_name='quote',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='ndthemes/quotes/'),
        ),
        migrations.AddField(
            model_name='quote',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='author_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='layout',
            field=models.CharField(choices=[('default', 'Default'), ('inline', 'Inline'), ('stacked', 'Stacked')], default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='quote',
            name='variant',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('primary', 'Primary')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='banner',
            name='layout',
            field=models.CharField(choices=[('stacked', 'Stacked'), ('default', 'Default (side by side)'), ('full', 'Full width'), ('cards', 'Cards'), ('accordion', 'Accordion'), ('gallery', 'Gallery'), ('mosaic', 'Mosaic'), ('tiled', 'Tiled')], default='stacked', max_length=16),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('text', models.CharField(max_length=255)),
                ('style', models.CharField(blank=True, choices=[('', 'Default'), ('cta', 'Call to action'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('neutral', 'Neutral'), ('more', 'More')], default='', max_length=16)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='Byline',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', help_text='Role or affiliation', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ndthemes/bylines/')),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='VideoButton',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=4096)),
                ('text', models.CharField(default='View video', max_length=255)),
                ('style', models.CharField(blank=True, choices=[('', 'Default'), ('minimal', 'Minimal'), ('ornamental', 'Ornamental'), ('outline', 'Outline')], default='', max_length=16)),
                ('link', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
