# Generated by Django 6.1 on 2026-08-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndthemes', '0009_m5_remaining_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='sticker',
            field=models.CharField(blank=True, choices=[('backpack', 'Backpack'), ('chalk-board', 'Chalk board'), ('dna', 'DNA'), ('football', 'Football'), ('globe', 'Globe'), ('grad-cap', 'Grad cap'), ('library', 'Library'), ('microscope', 'Microscope')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='stat',
            name='sticker_size',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('sm', 'Small'), ('lg', 'Large'), ('xl', 'Extra large')], default='', max_length=8),
        ),
    ]
