# Generated by Django 6.1 on 2026-08-12

import djangocms_text.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0043_alter_globalpagepermission_can_view_and_more"),
        ("ndthemes", "0010_stat_sticker_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardGrid",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.AlterField(
            model_name="cardperson",
            name="job_title",
            field=djangocms_text.fields.HTMLField(blank=True, default=""),
        ),
    ]
